version: '3.9'

services:
  mongo:
    image: mongo:4.4.10-focal
    ports:
      - 27017:27017
    volumes:
      - ~/DOCKERPROGRAMS:/DOCKERPROGRAMS
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

events:
    image: 
      build:
      ports:
      - 27018:27018
      volumes:
      - ~/DOCKERPROGRAMS:/DOCKERPROGRAMS
      environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root